#include <unity.h>

void test_pump_timeout();
void test_light_state();
void test_pump_start_ack();
void test_pump_stop_ack();
void test_pump_stop_command_after_start();
void test_reboot_declined_when_pump_running();
void test_reboot_accepted_when_idle();
void test_event_queue_order();
void test_parse_pump_start();
void test_parse_pump_stop();
void test_parse_reboot();
void test_parse_ota();
void test_parse_ota_rejects_external_url();
void test_parse_invalid_json();
void test_parse_missing_type();
void test_parse_invalid_duration();
void test_ack_payloads();
void test_scheduler_periodic();
void test_wifi_defaults_builtin();
void test_wifi_defaults_user_override();
void test_wifi_config_codec_storage();
void test_wifi_config_codec_invalid();
void test_wifi_config_encode_decode_list();
void test_webconfig_build_json();
void test_soil_scanner_detected();
void test_soil_scanner_hysteresis();
void test_sensor_hub_pump_block();
void test_sensor_hub_pauses_dht_while_pump_runs();
void test_state_soil_serialization();
void test_state_pump_status_and_started_at();
void test_state_publishes_on_pump_transition();
void test_state_started_at_null_without_time();
void test_dht_error_event_without_reboot();
void test_dht_read_failed_reports_error();
void test_dht_startup_grace_delays_disconnected();
void test_ota_pending_confirm();
void test_ota_boot_failures_trigger();
void test_ota_timeout_trigger();
void test_ota_install_success_ack_and_reboot();
void test_ota_install_error_ack();
void test_ota_declined_while_pump_runs();
void test_ota_installer_rejects_untrusted_url();
void test_dht_rate_limit();
void test_dht_nan_unavailable();
void test_dht_fail_triggers_reboot_event();
void test_device_identity_legacy_format();
void test_logger_prefix_no_watch();
void test_logger_prefix_synced();
void test_time_service_retry_schedule_on_fail();
void test_time_service_resync_schedule_on_success();
void test_mqtt_config_missing_and_invalid();
void test_mqtt_config_tls_time_gate_and_secret_free_log();
void test_mqtt_config_rejects_other_device_and_state_topic_is_scoped();

void setUp() {}
void tearDown() {}

int main(int argc, char** argv) {
  (void)argc;
  (void)argv;
  UNITY_BEGIN();
  RUN_TEST(test_pump_timeout);
  RUN_TEST(test_light_state);
  RUN_TEST(test_pump_start_ack);
  RUN_TEST(test_pump_stop_ack);
  RUN_TEST(test_pump_stop_command_after_start);
  RUN_TEST(test_reboot_declined_when_pump_running);
  RUN_TEST(test_reboot_accepted_when_idle);
  RUN_TEST(test_event_queue_order);
  RUN_TEST(test_parse_pump_start);
  RUN_TEST(test_parse_pump_stop);
  RUN_TEST(test_parse_reboot);
  RUN_TEST(test_parse_ota);
  RUN_TEST(test_parse_ota_rejects_external_url);
  RUN_TEST(test_parse_invalid_json);
  RUN_TEST(test_parse_missing_type);
  RUN_TEST(test_parse_invalid_duration);
  RUN_TEST(test_ack_payloads);
  RUN_TEST(test_scheduler_periodic);
  RUN_TEST(test_wifi_defaults_builtin);
  RUN_TEST(test_wifi_defaults_user_override);
  RUN_TEST(test_wifi_config_codec_storage);
  RUN_TEST(test_wifi_config_codec_invalid);
  RUN_TEST(test_wifi_config_encode_decode_list);
  RUN_TEST(test_webconfig_build_json);
  RUN_TEST(test_soil_scanner_detected);
  RUN_TEST(test_soil_scanner_hysteresis);
  RUN_TEST(test_sensor_hub_pump_block);
  RUN_TEST(test_sensor_hub_pauses_dht_while_pump_runs);
  RUN_TEST(test_state_soil_serialization);
  RUN_TEST(test_state_pump_status_and_started_at);
  RUN_TEST(test_state_publishes_on_pump_transition);
  RUN_TEST(test_state_started_at_null_without_time);
  RUN_TEST(test_dht_error_event_without_reboot);
  RUN_TEST(test_dht_read_failed_reports_error);
  RUN_TEST(test_dht_startup_grace_delays_disconnected);
  RUN_TEST(test_ota_pending_confirm);
  RUN_TEST(test_ota_boot_failures_trigger);
  RUN_TEST(test_ota_timeout_trigger);
  RUN_TEST(test_ota_install_success_ack_and_reboot);
  RUN_TEST(test_ota_install_error_ack);
  RUN_TEST(test_ota_declined_while_pump_runs);
  RUN_TEST(test_ota_installer_rejects_untrusted_url);
  RUN_TEST(test_dht_rate_limit);
  RUN_TEST(test_dht_nan_unavailable);
  RUN_TEST(test_dht_fail_triggers_reboot_event);
  RUN_TEST(test_device_identity_legacy_format);
  RUN_TEST(test_logger_prefix_no_watch);
  RUN_TEST(test_logger_prefix_synced);
  RUN_TEST(test_time_service_retry_schedule_on_fail);
  RUN_TEST(test_time_service_resync_schedule_on_success);
  RUN_TEST(test_mqtt_config_missing_and_invalid);
  RUN_TEST(test_mqtt_config_tls_time_gate_and_secret_free_log);
  RUN_TEST(test_mqtt_config_rejects_other_device_and_state_topic_is_scoped);
  return UNITY_END();
}
