version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: watering_db
      POSTGRES_USER: watering_user
      POSTGRES_PASSWORD: watering_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
