[growerhub_vps]
growerhub-vps ansible_host=91.218.246.67

[web:children]
growerhub_vps

[application:children]
growerhub_vps

[database:children]
growerhub_vps

[mqtt:children]
growerhub_vps

[vps:children]
growerhub_vps
