[growerhub_vps]
growerhub-vps ansible_host=135.106.184.20

[web:children]
growerhub_vps

[application:children]
growerhub_vps

[database:children]
growerhub_vps

[mqtt:children]
growerhub_vps

[vps:children]
growerhub_vps
