ansible_python_interpreter: /usr/bin/python3.12
server_timezone: "Europe/Moscow"
server_hostname: "growerhub"

app_user: watering-admin

google_client_id: "{{ lookup('env', 'GH_GOOGLE_CLIENT_ID') }}"
google_client_secret: "{{ lookup('env', 'GH_GOOGLE_CLIENT_SECRET') }}"
yandex_client_id: "{{ lookup('env', 'GH_YANDEX_CLIENT_ID') }}"
yandex_client_secret: "{{ lookup('env', 'GH_YANDEX_CLIENT_SECRET') }}"
