#include "services/website/WebsiteContent.h"

namespace Services {
namespace Website {

static const char kWebHtml[] =
    "<!doctype html>"
    "<html>"
    "<head>"
    "<meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    "<title>Wi-Fi setup</title>"
    "<link rel=\"stylesheet\" href=\"/style.css\">"
    "</head>"
    "<body>"
    "<div class=\"wrap\">"
    "<div class=\"card\">"
    "<h1>Wi-Fi setup</h1>"
    "<div class=\"status-block\">"
    "<div class=\"status-title\">Status</div>"
    "<div class=\"status-line\">{{WIFI_STATUS_LINE}}</div>"
    "<div class=\"status-line\">{{MQTT_STATUS_LINE}}</div>"
    "</div>"
    "<form id=\"net-form\">"
    "<label for=\"ssid\">SSID</label>"
    "<input id=\"ssid\" name=\"ssid\" maxlength=\"32\" autocomplete=\"off\"/>"
    "<label for=\"password\">Password</label>"
    "<input id=\"password\" name=\"password\" type=\"text\" maxlength=\"64\"/>"
    "<button type=\"submit\">Save</button>"
    "<div id=\"status\" class=\"status\" role=\"status\"></div>"
    "</form>"
    "<div class=\"list\">"
    "<div class=\"list-title\">Saved networks</div>"
    "<div id=\"networks\"></div>"
    "</div>"
    "</div>"
    "</div>"
    "<script src=\"/app.js\"></script>"
    "</body>"
    "</html>";

static const char kWebCss[] =
    "html, body { height: 100%; }\n"
    "body { margin: 0; font-family: \"Trebuchet MS\", \"Segoe UI\", sans-serif; "
    "font-size: 200%; background: #f0f4f6; color: #1b1b1b; }\n"
    ".wrap { min-height: 100%; display: flex; align-items: center; justify-content: center; "
    "padding: 1.5rem; }\n"
    ".card { width: 100%; max-width: 560px; background: #ffffff; border: 2px solid #1b1b1b; "
    "box-shadow: 8px 8px 0 #1b1b1b; padding: 1.5rem; }\n"
    "h1 { margin: 0 0 1rem 0; font-size: 1.2em; }\n"
    "label { display: block; margin-top: 0.75rem; }\n"
    "input { width: 100%; font-size: 1em; padding: 0.4rem 0.5rem; border: 2px solid #1b1b1b; }\n"
    "button { margin-top: 1rem; font-size: 1em; padding: 0.5rem 0.8rem; border: 2px solid #1b1b1b; "
    "background: #ffd35c; cursor: pointer; }\n"
    ".status { margin-top: 0.75rem; min-height: 1.2em; color: #0b5; font-weight: bold; }\n"
    ".status-block { margin: 0 0 1rem 0; padding: 0.6rem; border: 2px dashed #1b1b1b; "
    "background: #f9fbfc; font-family: \"Courier New\", monospace; font-size: 0.85em; }\n"
    ".status-title { font-weight: bold; margin-bottom: 0.25rem; }\n"
    ".status-line { margin-top: 0.2rem; }\n"
    ".list { margin-top: 1.5rem; border-top: 2px dashed #1b1b1b; padding-top: 1rem; }\n"
    ".list-title { font-weight: bold; margin-bottom: 0.5rem; }\n"
    ".net-row { display: flex; align-items: center; justify-content: space-between; gap: 0.5rem; "
    "margin-bottom: 0.5rem; }\n"
    ".net-name { font-weight: bold; }\n"
    ".net-pass { font-size: 0.9em; opacity: 0.75; }\n"
    ".net-del { font-size: 0.8em; padding: 0.3rem 0.6rem; background: #f2b6b6; border: 2px solid #1b1b1b; }\n";

static const char kWebJs[] =
    "const form = document.getElementById('net-form');\n"
    "const ssidInput = document.getElementById('ssid');\n"
    "const passInput = document.getElementById('password');\n"
    "const statusEl = document.getElementById('status');\n"
    "const listEl = document.getElementById('networks');\n"
    "\n"
    "function setStatus(text, ok) {\n"
    "  statusEl.textContent = text;\n"
    "  statusEl.style.color = ok ? '#0b5' : '#b00';\n"
    "}\n"
    "\n"
    "async function loadNetworks() {\n"
    "  const res = await fetch('/api/networks');\n"
    "  if (!res.ok) {\n"
    "    setStatus('Load error', false);\n"
    "    return;\n"
    "  }\n"
    "  const data = await res.json();\n"
    "  renderNetworks(data.networks || []);\n"
    "}\n"
    "\n"
    "function renderNetworks(networks) {\n"
    "  listEl.innerHTML = '';\n"
    "  if (networks.length === 0) {\n"
    "    const empty = document.createElement('div');\n"
    "    empty.textContent = 'No networks';\n"
    "    listEl.appendChild(empty);\n"
    "    return;\n"
    "  }\n"
    "  networks.forEach((net) => {\n"
    "    const row = document.createElement('div');\n"
    "    row.className = 'net-row';\n"
    "    const info = document.createElement('div');\n"
    "    const name = document.createElement('div');\n"
    "    name.className = 'net-name';\n"
    "    name.textContent = net.ssid || '';\n"
    "    const pass = document.createElement('div');\n"
    "    pass.className = 'net-pass';\n"
    "    pass.textContent = net.password || '';\n"
    "    info.appendChild(name);\n"
    "    info.appendChild(pass);\n"
    "    const del = document.createElement('button');\n"
    "    del.className = 'net-del';\n"
    "    del.type = 'button';\n"
    "    del.textContent = 'Delete';\n"
    "    del.addEventListener('click', async () => {\n"
    "      const resp = await fetch('/api/networks?ssid=' + encodeURIComponent(net.ssid || ''), { method: 'DELETE' });\n"
    "      if (resp.ok) {\n"
    "        setStatus('Sokhraneno', true);\n"
    "        loadNetworks();\n"
    "      } else {\n"
    "        const msg = await resp.text();\n"
    "        setStatus(msg || 'Delete error', false);\n"
    "      }\n"
    "    });\n"
    "    row.appendChild(info);\n"
    "    row.appendChild(del);\n"
    "    listEl.appendChild(row);\n"
    "  });\n"
    "}\n"
    "\n"
    "form.addEventListener('submit', async (e) => {\n"
    "  e.preventDefault();\n"
    "  const ssid = ssidInput.value.trim();\n"
    "  const password = passInput.value;\n"
    "  if (!ssid) {\n"
    "    setStatus('SSID required', false);\n"
    "    return;\n"
    "  }\n"
    "  const res = await fetch('/api/networks', {\n"
    "    method: 'POST',\n"
    "    headers: { 'Content-Type': 'application/json' },\n"
    "    body: JSON.stringify({ ssid, password })\n"
    "  });\n"
    "  if (res.ok) {\n"
    "    setStatus('Sokhraneno', true);\n"
    "    loadNetworks();\n"
    "  } else {\n"
    "    const msg = await res.text();\n"
    "    setStatus(msg || 'Save error', false);\n"
    "  }\n"
    "});\n"
    "\n"
    "loadNetworks();\n";

const char* Html() {
  return kWebHtml;
}

const char* Css() {
  return kWebCss;
}

const char* Js() {
  return kWebJs;
}

}
}
