# Tekushchij app-host.
[app]
192.168.0.11 ansible_user=watering-admin ansible_python_interpreter=/usr/bin/python3

# Upravlyayushchij uzel Ansible.
[ansible_host]
ansible-host ansible_host=192.168.0.80 ansible_user=gh

# GH-nody po rolyam.
[gh_db]
gh-db ansible_host=192.168.0.81 ansible_user=gh

[gh_app]
gh-app ansible_host=192.168.0.82 ansible_user=gh

[gh_nginx]
gh-nginx ansible_host=192.168.0.83 ansible_user=gh

[gh_mqtt]
gh-mqtt ansible_host=192.168.0.84 ansible_user=gh

[gh_tools]
gh-tools ansible_host=192.168.0.85 ansible_user=gh

[gh_all:children]
gh_db
gh_app
gh_nginx
gh_mqtt
gh_tools

[gh_prod:children]
gh_db
gh_app
gh_nginx
gh_mqtt
gh_tools
