const content = {
  ru: {
    details: 'Состав и цена',
    priceNote: 'Доставка рассчитывается отдельно',
    assembly: 'Собираем после подтверждения заказа',
    pilot: 'Mini · пока пилот, проверим перед поставкой',
    contents: 'В комплекте',
    add: 'Добавить в корзину',
    added: 'Добавлено в корзину',
    cart: 'Перейти в корзину',
    illustration: 'Иллюстрация состава. Лампы и растения не входят в комплект.',
    kitAlt: {
      'light-mini': 'Блок управления ПушОк Mini и одна умная розетка',
      'light-white': 'Блок управления ПушОк White и одна умная розетка',
      'light-three': 'Блок управления ПушОк White и три умные розетки',
    },
    catalogue: {
      title: 'Готовые комплекты для ваших растений',
      description: 'Выберите один стеллаж или несколько зон света. В комплекте — блок управления, умные розетки, питание и помощь с первым подключением.',
      eyebrow: 'От первого стеллажа до небольшого питомника',
      note: 'Вы пользуетесь своими лампами. Мы поможем с расписанием света.',
      compare: 'Какой комплект выбрать',
      compareIntro: 'Начните с количества зон света. Каждой розетке можно задать своё расписание.',
      comparing: [
        { id: 'light-mini', title: 'Один стеллаж, доступный старт', text: 'Mini и одна розетка для одной зоны света. Модель Mini ещё требует проверки с GrowerHub — поставку подтвердим после испытания.' },
        { id: 'light-white', title: 'Одна зона, больше запаса связи', text: 'White с усилителем сигнала и одна розетка. Реальная дальность зависит от стен и расположения устройств.' },
        { id: 'light-three', title: 'Три зоны, разные расписания', text: 'White и три розетки. Подойдёт, если рассаде, черенкам и взрослым растениям нужен свет в разное время.' },
      ],
      includedTitle: 'Сначала всё уточним, затем отправим',
      includedText: 'После заказа свяжемся с вами, согласуем комплект и доставку. Проверим устройства, приложим инструкцию и поможем с первым подключением. Сейчас оплачивать ничего не нужно.',
      deliveryTitle: 'Доставка СДЭК',
      deliveryText: 'Найдите удобный пункт выдачи на сайте СДЭК и укажите его номер и адрес при оформлении. Стоимость и срок доставки согласуем с вами отдельно.',
      limitsTitle: 'Что нужно дома',
      limits: ['Домашний Wi-Fi с интернетом и телефон для первого подключения.', 'Ваши лампы с подходящей для умной розетки нагрузкой — проверим перед подтверждением заказа.', 'Эти наборы управляют светом. Они не являются готовой системой автоматического полива.'],
      technical: 'Уже есть оборудование или хотите собрать сами?',
      technicalIntro: 'Готовый комплект необязателен. Здесь — модели устройств и подробности совместимости для самостоятельного выбора.',
      categoryLink: 'Посмотреть модели',
      pumpLink: 'О проекте насоса',
      compatibility: 'Совместимость зависит от модели и ревизии устройства. Проверка одной розетки не означает, что все Zigbee-устройства работают через ПушОк с GrowerHub.',
      checkedTitle: 'Что уже проверено',
      checkedText: 'С GrowerHub физически проверены ПушОк White POK100v2 с прошивкой 95 и розетка Zbeacon TS011F. Другие модели и конкретные ревизии требуют проверки. Перед подтверждением поставки проверим ваш комплект.',
    },
    start: {
      title: 'Начать можно с малого',
      description: 'Посмотрите готовый пример без покупок или выберите комплект для света по расписанию. С первым подключением GrowerHub поможем.',
      eyebrow: 'В вашем темпе, с нашей помощью',
      demoTitle: 'Сначала познакомиться',
      demoText: 'Ничего покупать и подключать не нужно. В демо уже есть растения и виртуальные устройства — можно посмотреть и попробовать.',
      demoCta: 'Открыть демоферму',
      kitTitle: 'Хочу свет по расписанию',
      kitText: 'Выберите комплект для одного стеллажа или нескольких зон. Мы проверим устройства, отправим и поможем подключить.',
      kitCta: 'Выбрать комплект',
      stepsTitle: 'Как подключим ваш комплект',
      stepsIntro: 'Часть подготовки сделаем перед отправкой. Дома понадобится телефон, домашний Wi-Fi с интернетом и немного времени на знакомство.',
      steps: [
        { title: 'Подключим блок управления к Wi-Fi', text: 'Включите ПушОк в питание и откройте «Управлятор» на телефоне. Приложение поможет указать домашнюю сеть и пароль.' },
        { title: 'Проверим умные розетки', text: 'Согласуем предварительную привязку розеток при подготовке. Дома проверим, что они видны в «Управляторе»; если нужно, поможем выполнить сопряжение.' },
        { title: 'Свяжем с GrowerHub', text: 'Войдите в GrowerHub, откройте «Подключения» и добавьте ПушОк по его ID. Для разрешения доступа нужно нажать кнопку на блоке управления — подскажем когда.' },
        { title: 'Настроим первый свет', text: 'Назначим розетку нужной зоне, выберем время включения и выключения, проверим работу вместе. Затем сможете менять расписание сами.' },
      ],
      connectionTitle: 'Что стоит знать заранее',
      connectionText: 'GrowerHub управляет через облако ПушОка: нужен интернет. Без связи новые команды из GrowerHub не дойдут до устройства. Перед подключением проверим лампы и нагрузку; насосы к этим комплектам не относятся.',
      helpTitle: 'Если что-то не получается — поможем',
      helpText: 'Не нужно разбираться во всём сразу. Расскажите о своих растениях и оборудовании — вместе выберем первый шаг.',
      helpCta: 'Помогите начать',
      technical: 'Уже есть ПушОк, Home Assistant или другое оборудование?',
      technicalIntro: 'Дополнительные способы подключения и подробные инструкции. Используйте свой комплект — покупать новый необязательно.',
      morePaths: 'Другие способы начать',
      existing: 'Уже есть Home Assistant?',
      monitoring: 'Только наблюдение',
      control: 'Управление',
      equipment: 'Проверить оборудование',
    },
  },
  en: {
    details: 'Contents and price',
    priceNote: 'Delivery is quoted separately',
    assembly: 'Prepared after your order is confirmed',
    pilot: 'Mini · a pilot, to be checked before supply',
    contents: 'Included in the kit',
    add: 'Add to basket',
    added: 'Added to basket',
    cart: 'View basket',
    illustration: 'Kit illustration. Lamps and plants are not included.',
    kitAlt: {
      'light-mini': 'PushOk Mini hub and one smart plug',
      'light-white': 'PushOk White hub and one smart plug',
      'light-three': 'PushOk White hub and three smart plugs',
    },
    catalogue: {
      title: 'Ready-to-order kits for your plants',
      description: 'Choose one shelf or several lighting zones. Each kit includes a hub, smart plugs, a power supply and help getting connected.',
      eyebrow: 'From your first shelf to a small nursery',
      note: 'Keep your own lamps. We will help you put the lighting on a schedule.',
      compare: 'Find the kit that suits you',
      compareIntro: 'Start with the number of lighting zones. Each plug can have its own schedule.',
      comparing: [
        { id: 'light-mini', title: 'One shelf, an affordable start', text: 'Mini and one plug for a single lighting zone. Mini still needs physical verification with GrowerHub; supply will be confirmed after testing.' },
        { id: 'light-white', title: 'One zone, extra radio capacity', text: 'White with a signal amplifier and one plug. Actual range depends on walls and device placement.' },
        { id: 'light-three', title: 'Three zones, separate schedules', text: 'White and three plugs. For seedlings, cuttings and mature plants that need light at different times.' },
      ],
      includedTitle: 'We will confirm the details before shipping',
      includedText: 'After your order, we will contact you to agree on the kit and delivery. We will check the devices, include instructions and help with your first connection. There is nothing to pay at this stage.',
      deliveryTitle: 'CDEK delivery',
      deliveryText: 'Find a convenient pickup point on the CDEK website and enter its code and address when ordering. We will confirm delivery costs and timing with you separately.',
      limitsTitle: 'What you need at home',
      limits: ['Home Wi-Fi with internet access and a phone for the initial connection.', 'Your own lamps with a load suitable for the smart plugs — we will check this before confirming your order.', 'These kits control lighting. They are not ready-made automated watering systems.'],
      technical: 'Already have hardware or want to build your own kit?',
      technicalIntro: 'You do not have to buy a kit. Explore individual devices and compatibility details for your own setup.',
      categoryLink: 'Explore devices',
      pumpLink: 'About the pump project',
      compatibility: 'Compatibility depends on the device model and revision. Testing one plug does not mean every Zigbee device works with GrowerHub through PushOk.',
      checkedTitle: 'What has been tested',
      checkedText: 'PushOk White POK100v2 with firmware 95 and a Zbeacon TS011F plug have been physically tested with GrowerHub. Other models and specific revisions need verification. We will check your kit before confirming supply.',
    },
    start: {
      title: 'Start with one small step',
      description: 'Explore an example without buying anything, or choose a kit for scheduled lighting. We will help you get connected to GrowerHub.',
      eyebrow: 'At your pace, with our help',
      demoTitle: 'Get to know the app first',
      demoText: 'There is nothing to buy or connect. The demo already has plants and virtual devices, ready to explore and try.',
      demoCta: 'Open the demo farm',
      kitTitle: 'I want scheduled lighting',
      kitText: 'Choose a kit for one shelf or several zones. We will check the devices, send them to you and help you connect them.',
      kitCta: 'Choose a kit',
      stepsTitle: 'How we will connect your kit',
      stepsIntro: 'We will prepare what we can before shipping. At home you will need a phone, home Wi-Fi with internet access and a little time to get familiar with the setup.',
      steps: [
        { title: 'Connect the hub to Wi-Fi', text: 'Power up PushOk and open the Upravlyator app on your phone. It will guide you through selecting your home network and entering its password.' },
        { title: 'Check your smart plugs', text: 'We will discuss pairing the plugs when preparing the kit. At home we will check that they appear in Upravlyator and help pair them if needed.' },
        { title: 'Link to GrowerHub', text: 'Sign in to GrowerHub, open Connections and add PushOk using its ID. Press the button on the hub to allow access — we will explain when.' },
        { title: 'Set up the first lighting schedule', text: 'Assign a plug to its zone, choose switch-on and switch-off times, and check that it works together. You can then adjust the schedule yourself.' },
      ],
      connectionTitle: 'A few things to know first',
      connectionText: 'GrowerHub controls devices through the PushOk cloud, so internet access is required. Without a connection, new GrowerHub commands will not reach the device. We will check your lamps and load before setup; these kits do not include pump control.',
      helpTitle: 'If you get stuck, we will help',
      helpText: 'You do not need to learn everything at once. Tell us about your plants and hardware, and we will choose a first step together.',
      helpCta: 'Help me get started',
      technical: 'Already have PushOk, Home Assistant or other hardware?',
      technicalIntro: 'Additional connection options and detailed instructions. Keep using your own hardware — you do not need to buy a new kit.',
      morePaths: 'Other ways to get started',
      existing: 'Already using Home Assistant?',
      monitoring: 'Monitoring only',
      control: 'Control',
      equipment: 'Check your hardware',
    },
  },
};

export const getNurseryCopy = (locale) => content[locale] || content.ru;

export const kitImages = {
  'light-mini': '/content/nursery/kit-mini.webp',
  'light-white': '/content/nursery/kit-white.webp',
  'light-three': '/content/nursery/kit-three.webp',
};
