const content = {
  ru: {
    details: 'Состав и цена',
    priceNote: 'Доставка рассчитывается отдельно',
    assembly: 'Собираем после подтверждения заказа',
    contents: 'В комплекте',
    add: 'Добавить в корзину',
    added: 'Добавлено в корзину',
    cart: 'Перейти в корзину',
    illustration: 'Иллюстрация. Состав перечислен в карточке; растения и горшки не входят в заказ.',
    configuration: 'Выберите комплектацию',
    pumpOnly: 'Только насос',
    pumpWithDrip: 'С 20 капельницами и шлангами',
    kitAlt: {
      'light-mini': 'Блок управления ПушОк Mini и одна умная розетка',
      'light-white': 'Блок управления ПушОк White и одна умная розетка',
      'light-three': 'Блок управления ПушОк White и три умные розетки',
      'soil-sensor': 'Иллюстрация датчика влажности почвы рядом с растением',
      pump: 'Иллюстрация насоса GrowerHub для полива',
      'pump-drip-kit': 'Иллюстрация насоса с капельницами и шлангами',
    },
    catalogue: {
      title: 'Готовые комплекты для ваших растений',
      description: 'Умные розетки для света, полива и вытяжки, датчик почвы и наш насос. Выберите то, что поможет вашим растениям, — с подключением поможем.',
      eyebrow: 'От первого стеллажа до небольшого питомника',
      note: 'Используйте свои приборы. Мы поможем подобрать подходящий сценарий.',
      compare: 'Какой комплект выбрать',
      compareIntro: 'Сколько приборов хотите включать автоматически? Каждой розетке можно назначить свою роль и сценарий.',
      comparing: [
        { id: 'light-mini', title: 'Один прибор, доступный старт', text: 'Mini и одна розетка. Начните с лампы, поливного насоса или вентилятора — что сейчас нужнее.' },
        { id: 'light-white', title: 'Одна зона, больше запаса связи', text: 'White с усилителем сигнала и одна розетка. Реальная дальность зависит от стен и расположения устройств.' },
        { id: 'light-three', title: 'Три прибора, свои сценарии', text: 'White и три розетки: для света, полива и вытяжки или трёх стеллажей с разным расписанием.' },
      ],
      includedTitle: 'Сначала всё уточним, затем отправим',
      includedText: 'После заказа свяжемся с вами, согласуем комплект и доставку. Проверим устройства, приложим инструкцию и поможем с первым подключением. Сейчас оплачивать ничего не нужно.',
      deliveryTitle: 'Доставка СДЭК',
      deliveryText: 'Найдите удобный пункт выдачи на сайте СДЭК и укажите его номер и адрес при оформлении. Стоимость и срок доставки согласуем с вами отдельно.',
      limitsTitle: 'Что нужно дома',
      limits: ['Домашний Wi-Fi с интернетом и телефон для первого подключения.', 'Лампы, вентиляторы и другие приборы подключаются через умные розетки — подходящую нагрузку обсудим с вами.', 'Для полива нужен насос и подача воды. Наш насос и капельный набор можно добавить отдельно.'],
      technical: 'Уже есть оборудование или хотите собрать сами?',
      technicalIntro: 'Готовый комплект необязателен. Здесь — модели устройств и подробности совместимости для самостоятельного выбора.',
      categoryLink: 'Посмотреть модели',
      pumpLink: 'Выбрать насос',
      compatibility: 'Расскажите, какое оборудование у вас уже есть. При подтверждении заказа подберём совместимые устройства и способ подключения.',
      checkedTitle: 'Видно, сколько расходуют приборы',
      checkedText: 'В GrowerHub можно открыть историю мощности и посмотреть энергопотребление за выбранный период. Эти данные доступны для розеток, которые передают измерения.',
      additionsTitle: 'Для полива и заботы о корнях',
      additionsIntro: 'Датчик почвы и насос можно заказать отдельно или добавить к комплекту. У насоса капельницы и шланги — на выбор.',
      additionsLink: 'Датчик почвы и насос',
    },
    start: {
      title: 'Начать можно с малого',
      description: 'Посмотрите готовый пример без покупок или выберите оборудование для света, полива и вентиляции. С первым подключением GrowerHub поможем.',
      eyebrow: 'В вашем темпе, с нашей помощью',
      demoTitle: 'Сначала познакомиться',
      demoText: 'Ничего покупать и подключать не нужно. В демо уже есть растения и виртуальные устройства — можно посмотреть и попробовать.',
      demoCta: 'Открыть демоферму',
      kitTitle: 'Хочу меньше ручных переключений',
      kitText: 'Начните с одного прибора или нескольких зон. Можно добавить датчик почвы или насос — подберём удобный вариант и поможем подключить.',
      kitCta: 'Выбрать комплект',
      stepsTitle: 'Как подключим ваш комплект',
      stepsIntro: 'Часть подготовки сделаем перед отправкой. Дома понадобится телефон, домашний Wi-Fi с интернетом и немного времени на знакомство.',
      steps: [
        { title: 'Подключим блок управления к Wi-Fi', text: 'Включите ПушОк в питание и откройте «Управлятор» на телефоне. Приложение поможет указать домашнюю сеть и пароль.' },
        { title: 'Проверим умные розетки', text: 'Согласуем предварительную привязку розеток при подготовке. Дома проверим, что они видны в «Управляторе»; если нужно, поможем выполнить сопряжение.' },
        { title: 'Свяжем с GrowerHub', text: 'Войдите в GrowerHub, откройте «Подключения» и добавьте ПушОк по его ID. Для разрешения доступа нужно нажать кнопку на блоке управления — подскажем когда.' },
        { title: 'Настроим первый сценарий', text: 'Назначим розетку нужному прибору: лампе, поливному насосу или вентилятору. Вместе выберем сценарий и проверим работу. Потом сможете менять настройки сами.' },
      ],
      connectionTitle: 'Что стоит знать заранее',
      connectionText: 'Для управления через ПушОк нужен интернет: без связи новые команды из GrowerHub не дойдут до устройства. Мощность приборов, подключение полива и подходящие сценарии обсудим перед первым запуском.',
      helpTitle: 'Если что-то не получается — поможем',
      helpText: 'Не нужно разбираться во всём сразу. Расскажите о своих растениях и оборудовании — вместе выберем первый шаг.',
      helpCta: 'Помогите начать',
      technical: 'Уже есть ПушОк, Home Assistant или другое оборудование?',
      technicalIntro: 'Дополнительные способы подключения и подробные инструкции. Используйте свой комплект — покупать новый необязательно.',
      morePaths: 'Другие способы начать',
      existing: 'Уже есть Home Assistant?',
      monitoring: 'Только наблюдение',
      control: 'Управление',
      equipment: 'Проверить оборудование',
    },
  },
  en: {
    details: 'Contents and price',
    priceNote: 'Delivery is quoted separately',
    assembly: 'Prepared after your order is confirmed',
    contents: 'Included in the kit',
    add: 'Add to basket',
    added: 'Added to basket',
    cart: 'View basket',
    illustration: 'Illustration. Included items are listed on the card; plants and pots are not included.',
    configuration: 'Choose what is included',
    pumpOnly: 'Pump only',
    pumpWithDrip: 'With 20 emitters and hoses',
    kitAlt: {
      'light-mini': 'PushOk Mini hub and one smart plug',
      'light-white': 'PushOk White hub and one smart plug',
      'light-three': 'PushOk White hub and three smart plugs',
      'soil-sensor': 'Illustration of a soil moisture sensor beside a plant',
      pump: 'Illustration of the GrowerHub watering pump',
      'pump-drip-kit': 'Illustration of a pump with drip emitters and hoses',
    },
    catalogue: {
      title: 'Ready-to-order kits for your plants',
      description: 'Smart plugs for lighting, watering and ventilation, a soil sensor and our pump. Choose what your plants need — we will help you get connected.',
      eyebrow: 'From your first shelf to a small nursery',
      note: 'Keep your own appliances. We will help you choose a suitable scenario.',
      compare: 'Find the kit that suits you',
      compareIntro: 'How many appliances would you like to control? Each plug can have its own role and scenario.',
      comparing: [
        { id: 'light-mini', title: 'One appliance, an affordable start', text: 'Mini and one plug. Start with a light, watering pump or fan — whichever helps you most.' },
        { id: 'light-white', title: 'One zone, extra radio capacity', text: 'White with a signal amplifier and one plug. Actual range depends on walls and device placement.' },
        { id: 'light-three', title: 'Three appliances, separate scenarios', text: 'White and three plugs: lighting, watering and ventilation, or three shelves with different schedules.' },
      ],
      includedTitle: 'We will confirm the details before shipping',
      includedText: 'After your order, we will contact you to agree on the kit and delivery. We will check the devices, include instructions and help with your first connection. There is nothing to pay at this stage.',
      deliveryTitle: 'CDEK delivery',
      deliveryText: 'Find a convenient pickup point on the CDEK website and enter its code and address when ordering. We will confirm delivery costs and timing with you separately.',
      limitsTitle: 'What you need at home',
      limits: ['Home Wi-Fi with internet access and a phone for the initial connection.', 'Connect your lights, fans or other appliances through smart plugs. We will discuss suitable loads with you.', 'Watering needs a pump and water supply. Our pump and drip kit can be added separately.'],
      technical: 'Already have hardware or want to build your own kit?',
      technicalIntro: 'You do not have to buy a kit. Explore individual devices and compatibility details for your own setup.',
      categoryLink: 'Explore devices',
      pumpLink: 'Choose a pump',
      compatibility: 'Tell us about your existing hardware. When confirming your order, we will choose compatible devices and a suitable connection together.',
      checkedTitle: 'See how much energy your appliances use',
      checkedText: 'GrowerHub shows power history and energy use for your selected period. These readings are available for plugs that report measurements.',
      additionsTitle: 'For watering and healthy roots',
      additionsIntro: 'Order a soil sensor or pump separately, or add them to a kit. Emitters and hoses are optional with the pump.',
      additionsLink: 'Soil sensor and pump',
    },
    start: {
      title: 'Start with one small step',
      description: 'Explore an example without buying anything, or choose equipment for lighting, watering and ventilation. We will help you get connected to GrowerHub.',
      eyebrow: 'At your pace, with our help',
      demoTitle: 'Get to know the app first',
      demoText: 'There is nothing to buy or connect. The demo already has plants and virtual devices, ready to explore and try.',
      demoCta: 'Open the demo farm',
      kitTitle: 'I want fewer manual switches',
      kitText: 'Start with one appliance or several zones. Add a soil sensor or pump if you need one — we will help you choose and connect it.',
      kitCta: 'Choose a kit',
      stepsTitle: 'How we will connect your kit',
      stepsIntro: 'We will prepare what we can before shipping. At home you will need a phone, home Wi-Fi with internet access and a little time to get familiar with the setup.',
      steps: [
        { title: 'Connect the hub to Wi-Fi', text: 'Power up PushOk and open the Upravlyator app on your phone. It will guide you through selecting your home network and entering its password.' },
        { title: 'Check your smart plugs', text: 'We will discuss pairing the plugs when preparing the kit. At home we will check that they appear in Upravlyator and help pair them if needed.' },
        { title: 'Link to GrowerHub', text: 'Sign in to GrowerHub, open Connections and add PushOk using its ID. Press the button on the hub to allow access — we will explain when.' },
        { title: 'Set up your first scenario', text: 'Assign a plug to a light, watering pump or fan. We will choose a scenario and check it together. You can then adjust the settings yourself.' },
      ],
      connectionTitle: 'A few things to know first',
      connectionText: 'Control through PushOk needs internet access: without a connection, new GrowerHub commands will not reach the device. We will discuss appliance loads, watering connections and suitable scenarios before the first setup.',
      helpTitle: 'If you get stuck, we will help',
      helpText: 'You do not need to learn everything at once. Tell us about your plants and hardware, and we will choose a first step together.',
      helpCta: 'Help me get started',
      technical: 'Already have PushOk, Home Assistant or other hardware?',
      technicalIntro: 'Additional connection options and detailed instructions. Keep using your own hardware — you do not need to buy a new kit.',
      morePaths: 'Other ways to get started',
      existing: 'Already using Home Assistant?',
      monitoring: 'Monitoring only',
      control: 'Control',
      equipment: 'Check your hardware',
    },
  },
};

export const getNurseryCopy = (locale) => content[locale] || content.ru;

export const kitImages = {
  'light-mini': '/content/nursery/kit-mini.webp',
  'light-white': '/content/nursery/kit-white.webp',
  'light-three': '/content/nursery/kit-three.webp',
  'soil-sensor': '/content/nursery/soil-sensor.webp',
  pump: '/content/nursery/pump.webp',
  'pump-drip-kit': '/content/nursery/pump-drip-kit.webp',
};
