ALTER TABLE sensor_data ADD COLUMN IF NOT EXISTS light_relay_on BOOLEAN;
ALTER TABLE sensor_data ADD COLUMN IF NOT EXISTS pump_relay_on BOOLEAN;
ALTER TABLE sensor_data ADD COLUMN IF NOT EXISTS soil_moisture_1 DOUBLE PRECISION;
ALTER TABLE sensor_data ADD COLUMN IF NOT EXISTS soil_moisture_2 DOUBLE PRECISION;