export const articleClusters = [
  {
    slug: 'avtopoliv-i-kontroller-vyrashchivaniya',
    title: 'Автополив и контроллер выращивания',
    description: 'Практические материалы о поливе, датчиках, реле, свете и безопасной автоматизации для дома, гроубокса и теплицы.',
    fit: 'У вас есть одна или несколько зон полива, а таймеров и ручных проверок уже недостаточно.',
    tasks: 'Выбор датчиков и исполнительных устройств, проверка расхода воды, лимиты одного запуска, паузы и аварийная остановка.',
    keywords: [
      'автополив для растений',
      'автоматический полив комнатных растений',
      'автополив для теплицы',
      'контроллер полива',
      'датчик влажности почвы для полива',
      'умный полив',
      'автоматизация полива',
      'полив по датчику влажности',
      'безопасный автополив',
      'гроубокс автоматизация',
    ],
    featuredArticles: [
      'avtopoliv-dlya-rasteniy-kak-vybrat',
      'kontroller-poliva-protiv-taymera',
      'datchik-vlazhnosti-pochvy-dlya-avtopoliva',
      'bezopasnyy-avtopoliv-limity-i-avariynyy-stop',
      'startovyy-komplekt-umnogo-poliva',
    ],
  },
  {
    slug: 'zhurnal-i-sovetnik-uhoda',
    title: 'Журнал и советник ухода',
    description: 'Раздел о дневнике растения, журнале полива, наблюдениях, графиках и аккуратных рекомендациях по уходу.',
    fit: 'Нужно сопоставлять состояние растений с поливами, показаниями датчиков и изменениями ухода, а не полагаться на память.',
    tasks: 'Структура журнала, отметки о поливах и обслуживании, чтение графиков и сравнение условий между циклами.',
    keywords: [
      'дневник растений',
      'журнал полива растений',
      'график полива растений',
      'уход за растениями по датчикам',
      'советы по поливу растений',
      'pH воды для растений',
      'подкормка растений',
      'фото дневник растений',
      'история микроклимата',
      'рекомендации по уходу за растениями',
    ],
    featuredArticles: [
      'dnevnik-rasteniya-chto-zapisyvat',
      'zhurnal-poliva-obem-ph-udobreniya',
      'pereliv-ili-nedoliv-po-dannym-datchika',
      'istoriya-mikroklimata-i-grafiki',
      'nedelnyy-plan-uhoda-za-rasteniyami',
    ],
  },
  {
    slug: 'zigbee-hub-i-ustroystva',
    title: 'Zigbee Hub и совместимые устройства',
    description: 'Материалы о Zigbee, Zigbee2MQTT, ролях устройств, датчиках, розетках и безопасном применении в зоне растений.',
    fit: 'У вас уже есть Zigbee или Zigbee2MQTT либо вы выбираете беспроводные датчики для теплицы, бокса или стеллажа.',
    tasks: 'Проверка совместимости, pairing, покрытие сети, availability, выбор датчиков, розеток и реле по реальной нагрузке.',
    keywords: [
      'Zigbee датчик температуры влажности',
      'Zigbee для теплицы',
      'Zigbee2MQTT',
      'умная розетка Zigbee для растений',
      'Zigbee датчик протечки',
      'Zigbee реле',
      'Zigbee датчик влажности',
      'совместимость Zigbee2MQTT',
      'умная теплица Zigbee',
      'Zigbee Hub',
    ],
    featuredArticles: [
      'zigbee-dlya-teplitsy-kakie-ustroystva-polezny',
      'zigbee2mqtt-prostymi-slovami',
      'podklyuchit-zigbee-datchik-temperatury-vlazhnosti',
      'zigbee-datchik-protechki-dlya-avtopoliva',
      'gotovyy-zigbee-hub-dlya-growerhub',
    ],
  },
  {
    slug: 'mini-ferma-i-neskolko-boksov',
    title: 'Несколько боксов и мини-ферма',
    description: 'Раздел для владельцев нескольких зон выращивания: мониторинг, аварии, учет ресурсов, роли пользователей и обслуживание.',
    fit: 'У вас несколько зон выращивания, и состояние датчиков, оборудования и поливов приходится собирать из разных интерфейсов.',
    tasks: 'Структура зон, единый обзор, история, обслуживание оборудования и самостоятельное подключение GrowerHub.',
    keywords: [
      'автоматизация теплицы',
      'мониторинг теплицы',
      'умная теплица для бизнеса',
      'мини ферма автоматизация',
      'контроль микроклимата теплицы',
      'удаленный контроль теплицы',
      'учет воды в теплице',
      'мониторинг нескольких теплиц',
      'уведомления в теплице',
      'система управления теплицей',
    ],
    featuredArticles: [
      'mini-ferma-iz-dvuh-grouboksov-dashboard',
      'avtomatizatsiya-teplitsy-chto-kontrolirovat',
      'monitoring-neskolkih-boksov',
      'uvedomleniya-v-mini-ferme',
      'masshtabirovanie-ot-boksa-do-mini-fermy',
    ],
  },
  {
    slug: 'home-assistant-i-diy',
    title: 'Home Assistant и DIY-интеграции',
    description: 'Технический раздел про Home Assistant, MQTT, ESP32, Zigbee2MQTT, локальные сценарии и границы DIY-автоматизации.',
    fit: 'Вы используете Home Assistant, ESP32, MQTT или Zigbee2MQTT и хотите связать DIY-часть с понятной моделью зон.',
    tasks: 'Калибровка датчиков, MQTT-топики и availability, границы ответственности систем, безопасные условия автоматизации.',
    keywords: [
      'Home Assistant автополив',
      'MQTT автополив',
      'ESP32 автополив Home Assistant',
      'MQTT discovery Home Assistant',
      'Home Assistant растения',
      'Zigbee2MQTT теплица',
      'dashboard растений Home Assistant',
      'Node-RED полив',
      'локальная автоматизация растений',
      'GrowerHub Home Assistant',
    ],
    featuredArticles: [
      'home-assistant-dlya-rasteniy',
      'mqtt-avtopoliv-kakie-topiki-nuzhny',
      'mqtt-discovery-home-assistant',
      'growerhub-i-home-assistant-cherez-mqtt',
      'diy-ili-gotovyy-kontroller-poliva',
    ],
  },
];

export const getArticleClusterBySlug = (slug) =>
  articleClusters.find((cluster) => cluster.slug === slug);
