"""init schema

Revision ID: 7ca2ce4d6f92
Revises: 
Create Date: 2025-11-19 12:44:12.495410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca2ce4d6f92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_state_last',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_device_state_last_device_id')
    )
    op.create_index(op.f('ix_device_state_last_id'), 'device_state_last', ['id'], unique=False)
    op.create_index('ix_device_state_last_updated_at', 'device_state_last', ['updated_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('air_humidity', sa.Float(), nullable=True),
    sa.Column('is_watering', sa.Boolean(), nullable=True),
    sa.Column('is_light_on', sa.Boolean(), nullable=True),
    sa.Column('last_watering', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('target_moisture', sa.Float(), nullable=True),
    sa.Column('watering_duration', sa.Integer(), nullable=True),
    sa.Column('watering_timeout', sa.Integer(), nullable=True),
    sa.Column('light_on_hour', sa.Integer(), nullable=True),
    sa.Column('light_off_hour', sa.Integer(), nullable=True),
    sa.Column('light_duration', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('latest_version', sa.String(), nullable=True),
    sa.Column('update_available', sa.Boolean(), nullable=True),
    sa.Column('firmware_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('mqtt_ack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id', name='uq_mqtt_ack_correlation_id')
    )
    op.create_index('ix_mqtt_ack_device_id', 'mqtt_ack', ['device_id'], unique=False)
    op.create_index('ix_mqtt_ack_expires_at', 'mqtt_ack', ['expires_at'], unique=False)
    op.create_index(op.f('ix_mqtt_ack_id'), 'mqtt_ack', ['id'], unique=False)
    op.create_index('ix_mqtt_ack_received_at', 'mqtt_ack', ['received_at'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('air_humidity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_device_id'), 'sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_data_timestamp'), 'sensor_data', ['timestamp'], unique=False)
    op.create_table('watering_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('water_used', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_logs_device_id'), 'watering_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_watering_logs_id'), 'watering_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watering_logs_id'), table_name='watering_logs')
    op.drop_index(op.f('ix_watering_logs_device_id'), table_name='watering_logs')
    op.drop_table('watering_logs')
    op.drop_index(op.f('ix_sensor_data_timestamp'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_device_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index('ix_mqtt_ack_received_at', table_name='mqtt_ack')
    op.drop_index(op.f('ix_mqtt_ack_id'), table_name='mqtt_ack')
    op.drop_index('ix_mqtt_ack_expires_at', table_name='mqtt_ack')
    op.drop_index('ix_mqtt_ack_device_id', table_name='mqtt_ack')
    op.drop_table('mqtt_ack')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_device_state_last_updated_at', table_name='device_state_last')
    op.drop_index(op.f('ix_device_state_last_id'), table_name='device_state_last')
    op.drop_table('device_state_last')
    # ### end Alembic commands ###
