- name: Configure GrowerHub Deploy Agent
  hosts: growerhub_server
  become: true

  vars_prompt:
    - name: github_token
      prompt: "Введите GitHub token"
      private: no

  vars:
    growerhub_da_manage_user: false
    growerhub_da_user: watering-admin
    growerhub_da_group: watering-admin
    growerhub_da_protect_home: false
    growerhub_da_workdir: /home/watering-admin/growerhub
    growerhub_da_exec_start: /home/watering-admin/growerhub/server/.venv/bin/python -m deploy_agent
    growerhub_da_env:
      GITHUB_TOKEN: "{{ github_token }}"
      GROWERHUB_REPO_URL: "https://github.com/aspinozaxxx-lab/growerhub"
      GROWERHUB_BRANCH: "main"
      GROWERHUB_POLL_INTERVAL: "30"
      GROWERHUB_WORKDIR: "{{ growerhub_da_workdir }}"

  roles:
    - role: growerhub_deploy_agent

