name: Deploy over SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Sync project to server
        run: |
          RSYNC_RSH="ssh -p 6733 -o StrictHostKeyChecking=yes"
          rsync -az --delete --exclude ".git" ./ watering-admin@growerhub.ru:/home/watering-admin/growerhub/

      - name: Remote build & restart
        run: |
          ssh -p 6733 watering-admin@growerhub.ru <<'EOF'
          set -e
          cd ~/growerhub/server
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          sudo systemctl daemon-reload || true
          sudo systemctl restart growerhub.service
          systemctl status growerhub.service --no-pager || true
          EOF
