name: Deploy over SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 6733 growerhub.ru > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Ensure target dir exists (SSH)
        run: |
          ssh -p 6733 -o StrictHostKeyChecking=yes watering-admin@growerhub.ru "mkdir -p /home/watering-admin/growerhub && chmod 755 /home/watering-admin/growerhub"

      - name: SSH smoke test
        run: |
          ssh -p 6733 -o StrictHostKeyChecking=yes watering-admin@growerhub.ru "echo 'SSH connection OK'"

      - name: Sync project to server (robust)
        run: |
          rsync -azv --delete \
            --exclude ".git/" \
            --exclude ".venv/" \
            --exclude "__pycache__/" \
            --exclude "*.pyc" \
            --omit-dir-times --no-perms --no-owner --no-group \
            -e "ssh -p 6733 -o StrictHostKeyChecking=yes" \
            ./ watering-admin@growerhub.ru:/home/watering-admin/growerhub/

      - name: Remote build & restart
        run: |
          ssh -p 6733 watering-admin@growerhub.ru <<'EOF'
          set -e
          cd ~/growerhub/server
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          sudo systemctl daemon-reload || true
          sudo systemctl restart growerhub.service
          systemctl status growerhub.service --no-pager || true
          EOF
